<?php

/**
 * @file
 * Contains twig_block.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
// 
/**
 * Implements hook_help().
 */
function twig_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twig_block module.
    case 'help.page.twig_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('custom module to add your own blocks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function twig_block_form_alter(&$form, $form_state, $form_id) {

  // Look for any form provided by the contact module.
  // If you want to target a specific form you'll use the whole form ID
  // (e.g. Website feedback = 'contact_message_feedback_form').
  if (strpos($form_id, 'contact_message_feedback_form') !== FALSE) {
    $form['actions']['preview']['#access'] = FALSE;
    $form['actions']['submit']['#attributes']['class'][] = 'btn btn-primary btn-xl text-uppercase';
  }
}


function twig_block_theme($existing, $type, $theme, $path) {


$variables = array(
    'bloque' =>array(
      'variables' => array(
                  'title' => 'Default title',
                  'description' => null
                  ),
      'template' => 'bloque',
    ),             
    'masthead' =>array(
      'variables' => array(
                  'title' => 'masthead',
                  'description' => null
                  ),
      'template' => 'masthead',
    ),      
    'services' =>array(
      'variables' => array(
                  'title' => 'services',
                  'description' => null
                  ),
      'template' => 'services',
    ),       
    'contact' =>array(
      'variables' => array(
                  'title' => 'contact',
                  'description' => null
                  ),
      'template' => 'contact',
    ),                  
  );

  return $variables;


}
